# Use the official MySQL image as a base
FROM mysql:5.7.28

# Set environment variables
ENV MYSQL_DATABASE=devopsclass
ENV MYSQL_USER=ranjit
ENV MYSQL_PASSWORD=Sunday@2019
ENV MYSQL_ROOT_PASSWORD=Sunday@2019

# Copy initialization scripts (if any)
COPY ./dump /docker-entrypoint-initdb.d

# Expose the MySQL port
EXPOSE 3306
